web:
  image: droptica/drupal-apache
  volumes:
    - ./app:/var/www/html
  links:
    - mysql:mysql
  environment:
    VIRTUAL_HOST: {{HOST}},www.{{HOST}}

mysql:
  image: mysql:5.6
  volumes:
    - ./docker/custom_config/my.cnf:/etc/mysql/conf.d/custom.cnf:ro
  environment:
    MYSQL_ROOT_PASSWORD: 123
    MYSQL_DATABASE: db
    MYSQL_USER: user
    MYSQL_PASSWORD: pass

phpmyadmin:
  image: nazarpc/phpmyadmin
  links:
    - mysql:mysql
  environment:
      VIRTUAL_HOST: phpmyadmin.{{HOST}}